name: Deploy to Hostdata
on:
  push:
    branches: [ production ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: üöÄ Deploy Folder Aplikasi (Private)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Mengambil semua file project dari GitHub
          server-dir: /home/cahyofmy/domains/cahyof30.my.id/inventory_app/
          exclude: |
            **/public/**
            .git*
            .github/workflows/**

      - name: üåê Deploy Folder Public ke Subdomain (Public)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/ # Hanya mengambil isi folder 'public' dari GitHub
          server-dir: /home/cahyofmy/domains/cahyof30.my.id/public_html/inventory/